// This file is generated by icon spritesheet generator

export const iconNames = [
	'XCircle',
	'Transactions',
	'Sort',
	'RecurringBills',
	'RecurringBillsOutline',
	'Pots',
	'Overview',
	'Filter',
	'Exclamation',
	'Ellipsis',
	'Check',
	'CaretRight',
	'CaretLeft',
	'CaretDown',
	'Budgets',
] as const

export type IconName = (typeof iconNames)[number]
