// This file is generated by icon spritesheet generator

export const iconNames = [
	'Transactions',
	'RecurringBills',
	'Pots',
	'Overview',
	'CaretDown',
	'Budgets',
] as const

export type IconName = (typeof iconNames)[number]
